
services:
    server:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./server:/server
        ports:
            - 8000:8000
        depends_on:
            - db


    db:
        image: mysql:8
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'db_django'
            MYSQL_USER: 'mysql'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'

        restart: always
        volumes:
            - ./db_django:/var/lib/mysql
            - /tmp/app/mysqld:/run/mysqld
