# Generated by Django 4.1 on 2024-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['custom_ordering']},
        ),
        migrations.AddField(
            model_name='picture',
            name='custom_ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
